// This file was automatically generated by noise-serde-lib.
import Foundation
import NoiseBackend
import NoiseSerde

public struct Counter: Identifiable, Readable, Sendable, Writable {
  public let id: UVarint
  public let label: String
  public let value: Varint

  public init(
    id: UVarint,
    label: String,
    value: Varint
  ) {
    self.id = id
    self.label = label
    self.value = value
  }

  public static func read(from inp: InputPort, using buf: inout Data) -> Counter {
    return Counter(
      id: UVarint.read(from: inp, using: &buf),
      label: String.read(from: inp, using: &buf),
      value: Varint.read(from: inp, using: &buf)
    )
  }

  public func write(to out: OutputPort) {
    id.write(to: out)
    label.write(to: out)
    value.write(to: out)
  }
}

public final class Backend: Sendable {
  let impl: NoiseBackend.Backend!

  init(withZo zo: URL, andMod mod: String, andProc proc: String) {
    impl = NoiseBackend.Backend(withZo: zo, andMod: mod, andProc: proc)
  }

  public func createCounter(labeled label: String) -> Future<String, Counter> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0000).write(to: out)
        label.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Counter in
        return Counter.read(from: inp, using: &buf)
      }
    )
  }

  public func createCounter(labeled label: String) async throws -> Counter {
    return try await FutureUtil.asyncify(createCounter(labeled: label))
  }

  public func deleteCounter(forId id: UVarint) -> Future<String, Bool> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0001).write(to: out)
        id.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Bool in
        return Bool.read(from: inp, using: &buf)
      }
    )
  }

  public func deleteCounter(forId id: UVarint) async throws -> Bool {
    return try await FutureUtil.asyncify(deleteCounter(forId: id))
  }

  public func getAllCounters() -> Future<String, [Counter]> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0002).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> [Counter] in
        return [Counter].read(from: inp, using: &buf)
      }
    )
  }

  public func getAllCounters() async throws -> [Counter] {
    return try await FutureUtil.asyncify(getAllCounters())
  }

  public func getCounter(forId id: UVarint) -> Future<String, Counter?> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0003).write(to: out)
        id.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Counter? in
        return Counter?.read(from: inp, using: &buf)
      }
    )
  }

  public func getCounter(forId id: UVarint) async throws -> Counter? {
    return try await FutureUtil.asyncify(getCounter(forId: id))
  }

  public func incrementCounter(forId id: UVarint) -> Future<String, Counter?> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0004).write(to: out)
        id.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Counter? in
        return Counter?.read(from: inp, using: &buf)
      }
    )
  }

  public func incrementCounter(forId id: UVarint) async throws -> Counter? {
    return try await FutureUtil.asyncify(incrementCounter(forId: id))
  }

  public func installCallback(internalWithId id: UVarint, andAddr addr: Varint) -> Future<String, Void> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0005).write(to: out)
        id.write(to: out)
        addr.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Void in }
    )
  }

  public func installCallback(internalWithId id: UVarint, andAddr addr: Varint) async throws -> Void {
    return try await FutureUtil.asyncify(installCallback(internalWithId: id, andAddr: addr))
  }
}
